# https://taskfile.dev

version: "3"

tasks:
  api:
    dir: ./api
    env:
      HOST: 0.0.0.0:3000
    dotenv:
      - ./.env
    cmds:
      - cargo run
  api-lint:
    dir: ./api
    cmds:
      - cargo clippy
  ui:
    dir: ./ui
    cmds:
      - bun run dev
